### ISSUE TITLE
mac m1

### ISSUE THREAD

**Issue by zyxcambridge** [apeatling/ollama-voice-mac#1] opened 2023-12-31 04:21 UTC
(base) zhangyixin@zhangyixin Downloads % ollama pull mistral
pulling manifest 
Error: pull model manifest: Get "https://registry.ollama.ai/v2/library/mistral/manifests/latest": dial tcp: lookup registry.ollama.ai: no such host

**Comment by apeatling** [comment] 2023-12-31 05:53
Something might have changed with the API. I’ll check tomorrow. Does `ollama run mistral` work for you? That will pull the model first.

**Comment by arunsathiya** [comment] 2024-01-02 20:34
It works okay at my end. 

The error message that you are seeing suggests DNS resolution failure. Could you try flushing DNS and browser cache? Also  try changing your DNS resolver to something else like [Google](https://developers.google.com/speed/public-dns), [Cloudflare](https://1.1.1.1/), or [Quad9](https://quad9.net/)?

**Comment by apeatling** [comment] 2024-01-02 20:35
Yes also confirmed `ollama pull mistral` continues to work for me.

**Comment by apeatling** [comment] 2024-01-02 20:48
Closing this one since I don't think it's a general issue, but reopen if you have any more details.

**Closed as completed by apeatling** 2024-01-02 20:48 UTC
